### ISSUE TITLE
Setup continuous build

### ISSUE THREAD

**Issue by benmccann** [stonexx/sbt-webpack#11]
It'd be nice to have a test suite run automatically to validate pull requests. Travis is free for open source projects and pretty easy to setup. Most of the Lightbend plugins use it, so there's lots of examples as well

**Comment by stonexx** [comment]
added [travis](https://github.com/stonexx/sbt-webpack/commit/859f6ec932d7f2bcef29afe65bf9ae4bc5d5cc7a)

**Comment by benmccann** [comment]
wow, that's awesome! thank you!
