### ISSUE TITLE
Compile JSX code to Javascript, and bundle them together

### ISSUE THREAD

**Issue by Yvvann** [stonexx/sbt-webpack#12]
Dear friends, first of all, thanks for your wonderful work!!
I need the SBT-Webpack Plugin for:
- Compile JSX code to Javascript as defined in webpack.config.js

- Bundle the Javascipt code together

- And execute some scripts(Webpack commands) as defined in package.json

Is this posible with SBT-Webpack Plugin?
Thanks in advance!!

**Comment by stonexx** [comment]
I'm not considering `npm run` for the scripts defined in package.json.
Instead, use another plugin such as [sbt-npm](https://github.com/timt/sbt-npm).
thx.
