### ISSUE TITLE
The TypeScript Sources are copied to Target

### ISSUE THREAD

**Issue by mickeyvip** [stonexx/sbt-webpack#3]
The plugin works, but there are several caveats:

1. The `.ts` sources are copied to `target/web/public/main`
2. The suggested config with `output.path` set to `/target/web/webpack` makes the file not to be found by routes `<script src="@routes.Assets.versioned("webpack/bundle.js")" type="text/javascript"></script>`. (workaround: set the path to `path.join(__dirname, '/target/web/public/main/javascripts')` and use `<script src="@routes.Assets.versioned("javascripts/bundle.js")" type="text/javascript"></script>`)
3. Now we need to run separated `webpack:startWatch` command. How can we cause the plugin to run when we build the project?

**Comment by mickeyvip** [comment]
Also, in order for the SbtWeb plugins to work with generated files, we need to output not to the `target/...` but to the `/public/javascripts`:

```
output: {
		filename: 'bundle.js',
		path: path.join(__dirname, '/public/javascripts')
	},
```

**Comment by stonexx** [comment]
Thank you for your feedback.

If you want to run the webpack before another task. For example with build.sbt:
- WebKeys.pipeline := WebKeys.pipeline.dependsOn(run in Webpack).value
- packageBin := packageBin.dependsOn(run in Webpack).value

If you have other solutions, I would appreciate your advice.

**Comment by stonexx** [comment]
If you don't want `.ts` sources are copied to `target/web/public/main`:

- Move the `context` setting of the webpack elsewhere. example with `webpack.config.js`: `{ context: path.join(__dirname, '/web') }`

Then use `ts-loader`. example with `webpack.config.js`:
```javascript
const path = require('path');

module.exports = {
  context: path.join(__dirname, '/web'),
  entry: './app.ts',
  output: {
    path: path.join(__dirname, '/public/bundles'),
    filename: 'app.bundle.js'
  },
  resolve: {
    // Add `.ts` and `.tsx` as a resolvable extension.
    extensions: ['', '.webpack.js', '.web.js', '.ts', '.tsx', '.js']
  },
  module: {
    loaders: [
      // all files with a `.ts` or `.tsx` extension will be handled by `ts-loader`
      { test: /\.tsx?$/, loader: 'ts-loader' }
    ]
  }
}
```

thanks.
