### ISSUE TITLE
Expected assets location

### ISSUE THREAD

**Issue by benmccann** [stonexx/sbt-webpack#8]
I see you have assets in src/main/web:
https://github.com/stonexx/sbt-webpack/tree/master/sbt-webpack-tester/src/main/web/js

https://github.com/sbt/sbt-web says that it looks for
> files that are available for processing from src/main/assets

Why are these different? Is there a setting that's different between the two?

**Comment by stonexx** [comment]
If set to `src/main/assets`, it will work unnecessarily on sbt-web.

I thought sbt-web's work was unnecessary, so I set it as `src/main/web`.

If you have a better idea, I would appreciate your advice.
